# Generated by Django 5.0.14 on 2026-08-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text="Shopkeeper's WhatsApp number in normalized format, e.g. 919348957645 (country code + number, no + or spaces)", max_length=20),
        ),
    ]
