# Generated by Django 5.0.14 on 2026-08-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_add_whatsapp_number_to_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='qr_code_image',
            field=models.URLField(blank=True, default='', help_text="Direct URL to shopkeeper's static QR code if available"),
        ),
        migrations.AddField(
            model_name='shop',
            name='upi_id',
            field=models.CharField(blank=True, default='', help_text="Shopkeeper's UPI VPA / ID (e.g. 9853000001@paytm, rohitshop@okaxis)", max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='upi_name',
            field=models.CharField(blank=True, default='', help_text='Payee Name displayed on UPI payment screen', max_length=255),
        ),
    ]
