# Generated by Django 5.0.14 on 2026-08-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
        ('shops', '0002_add_whatsapp_number_to_shop'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_shop_product_inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('shop', 'product', 'variant'), name='unique_shop_product_variant_inventory'),
        ),
    ]
