# Generated by Django 5.0.14 on 2026-08-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_options_reservationitem_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('UPI_QR', 'UPI QR Code'), ('CASH', 'Cash on Pickup')], default='UPI_QR', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='UPI Transaction ID / UTR number', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('ACCEPTED', 'Accepted'), ('READY', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
