# Generated by Django 5.0.14 on 2026-08-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error details if sending failed (never shown to students)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', help_text='WhatsApp Cloud API message ID returned on successful dispatch', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('MOCK', 'Mock (Dev Mode — No Real Message Sent)')], default='PENDING', max_length=20),
        ),
    ]
