# Generated by Django 5.0.14 on 2026-08-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_mock_status_and_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('NOT_CONFIGURED', 'Not Configured (Missing Credentials)'), ('MOCK', 'Mock (Dev Mode — No Real Message Sent)')], default='PENDING', max_length=20),
        ),
    ]
